export default {
  attendEventButton: {
    fontSize: 15,
    color: '54ae33',
  },
  attendEventButtonContainer: {
    margin: 5,
    padding: 10,
    backgroundColor: '#fff',
    borderColor: '#54ae33',
    borderRadius: 8,
    borderWidth: 2,
    alignItems: 'center',
  },
  buttonContianer: {
    display: 'flex',
    alignContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonElement: {
    marginRight: 5,
    marginLeft: 5,
  },
  centeredText: {
    textAlign: 'center',
    marginTop: 5,
  },
  dateInputButton: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: 'gray',
    width: 200,
    padding: 10,
    textAlign: 'center',
    fontSize: 16,
  },
  dateInputContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 25,
  },
  descInput: {
    height: 130,
    width: '80%',
    padding: 10,
    marginBottom: 30,
    textAlign: 'center',
    borderColor: 'gray',
    borderRadius: 6,
    borderWidth: 1,
    marginLeft: 40,
  },
  detailPrimaryHeading: {
    textAlign: 'center',
    fontSize: 23,
    paddingTop: 10,
  },
  detailSecondaryHeading: {
    textAlign: 'center',
    width: '100%',
    paddingLeft: 15,
  },
  eventTypeButton: {
    margin: 5,
    padding: 10,
    backgroundColor: '#54ae33',
    borderRadius: 8,
    alignItems: 'center',
  },
  eventTypeButtonText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#fff',
  },
  infoTile: {
    width: '85%',
    height: 150,
    backgroundColor: '#54ae33',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    marginLeft: 30,
  },
  imageSelected: {
    width: '100%',
    height: 200,
    margin: 0,
  },
  mainContainer: {
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  mapPreviewTile: {
    width: '95%',
    height: 175,
    backgroundColor: '#54ae33',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    marginTop: 10,
    marginLeft: 8,
  },
  paragraph: {
    textAlign: 'left',
    width: '100%',
    paddingLeft: 15,
    paddingRight: 15,
  },
  previewHeading: {
    textAlign: 'center',
    fontSize: 20,
    marginTop: 15,
    marginBottom: 15,
  },
  primaryHeading: {
    textAlign: 'center',
    fontSize: 25,
    marginTop: 50,
    marginBottom: 50,
  },
  progressBar: {
    marginTop: 50,
  },
  subheading: {
    textAlign: 'left',
    width: '100%',
    fontSize: 15,
    fontWeight: 'bold',
    paddingTop: 20,
    paddingLeft: 15,
  },
  textInput: {
    height: 40,
    width: '80%',
    textAlign: 'center',
    borderColor: 'gray',
    borderRadius: 6,
    borderWidth: 1,
    marginBottom: 50,
    marginLeft: 40,
  },
  topTile: {
    width: '100%',
    height: 150,
    backgroundColor: '#54ae33',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
  },
  urlHeading: {
    textAlign: 'left',
    width: '100%',
    fontSize: 15,
    fontWeight: 'bold',
    paddingLeft: '10%',
    paddingBottom: 10,
  },
};
