import { Platform, StatusBar } from 'react-native';

export default {
  mainContainer: {
    flex: 1,
    alignItems: 'stretch',
    width: 300,
    paddingHorizontal: 25,
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  buttonContianer: {
    display: 'flex',
    alignContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  flagTypeContainer: {
    marginBottom: 50,
  },
  progressBar: {
    marginTop: 50,
  },
  textInput: {
    height: 40,
    width: '80%',
    textAlign: 'center',
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 6,
    marginBottom: 25,
    marginLeft: 22,
  },
  descInput: {
    height: 100,
    width: 300,
    padding: 10,
    marginHorizontal: '15%',
    marginBottom: '7%',
    textAlign: 'left',
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 6,
  },
  primaryHeading: {
    textAlign: 'center',
    fontSize: 25,
    marginTop: 50,
    marginBottom: 40,
  },
  paragraph: {
    textAlign: 'center',
    width: '100%',
  },
  previewHeading: {
    textAlign: 'center',
    fontSize: 20,
    marginTop: 15,
    marginBottom: 15,
  },
  centeredText: {
    textAlign: 'center',
    marginTop: 5,
  },
  paragraph: {
    textAlign: 'left',
    width: '100%',
    paddingLeft: 15,
    paddingRight: 15,
  },
  subheading: {
    textAlign: 'left',
    width: '100%',
    fontSize: 15,
    fontWeight: "bold",
    paddingTop: 20,
    paddingLeft: 15,
  },
  mapPreviewTile: {
    width: '95%',
    height: 175,
    backgroundColor: '#54ae33',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    marginVertical: 10,
    marginLeft: 8,
  },
  typeElement: {
    marginRight: 5,
    marginLeft: 5,
    backgroundColor: '#54ae33',
  },
};
