import { Platform, StatusBar, StyleSheet } from 'react-native';

export default StyleSheet.create({
  createButton: {
    marginLeft: 15,
    marginTop: 25,
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: '#54ae33',
    width: 100,
    borderRadius: 8,
    alignItems: 'center',
  },
  createButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
  },
  mainContainer: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  paragraph: {
    textAlign: 'center',
    width: '100%',
    paddingLeft: 15,
    paddingRight: 15,
  },
  primaryHeading: {
    textAlign: 'center',
    fontSize: 23,
    paddingTop: 10,
  },
  regButtonStyle: {
    display: 'flex',
    alignContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 25,
    paddingBottom: 75,
  },
  regHeading: {
    textAlign: 'center',
    fontSize: 25,
    marginTop: 50,
    marginBottom: 25,
  },
  regSecondaryHeading: {
    textAlign: 'center',
    width: '100%',
    paddingLeft: 15,
    paddingRight: 15,
    fontSize: 15,
    marginBottom: 8,
    marginTop: 15,
  },
  regSubheading: {
    textAlign: 'center',
    marginTop: 5,
    marginBottom: 25,
    padding: 10,
    width: '75%',
    fontSize: 15,
    fontWeight: "bold",
  },
  regTextInput: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 8,
    width: '50%',
    marginHorizontal: '25%',
  },
  subheading: {
    textAlign: 'center',
    width: '100%',
    fontSize: 15,
    fontWeight: "bold",
    paddingTop: 20,
    paddingLeft: 15,
  },
});
