import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  attendMessButton: {
    fontSize: 16,
    color: '#54ae33',
    fontWeight: 'bold',
  },
  attendMessButtonContainer: {
    marginHorizontal: '33.33%',
    marginVertical: 5,
    padding: 10,
    backgroundColor: '#fff',
    borderColor: '#54ae33',
    borderRadius: 8,
    borderWidth: 2,
    alignItems: 'center',
    width: 150,
  },
  buttonContainer: {
    display: 'flex',
    alignContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 75,
  },
  buttonElement: {
    marginRight: 5,
    marginLeft: 5,
  },
  centeredText: {
    textAlign: 'center',
    marginTop: 5,
  },
  detailPrimaryHeading: {
    textAlign: 'center',
    fontSize: 23,
    paddingTop: 10,
  },
  detailSecondaryHeading: {
    textAlign: 'center',
    width: '100%',
    paddingLeft: 15,
    fontWeight: 'bold',
  },
  descInput: {
    height: 130,
    width: 300,
    padding: 10,
    marginBottom: 30,
    textAlign: 'left',
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 6,
  },
  messTypeButton: {
    margin: 5,
    padding: 10,
    backgroundColor: '#fff',
    borderColor: '#000',
    borderRadius: 8,
    borderWidth: 2,
    alignItems: 'center',
  },
  messTypeButtonText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#000',
  },
  messTypeButtonSelected: {
    margin: 5,
    padding: 10,
    backgroundColor: '#54ae33',
    borderColor: '#54ae33',
    borderRadius: 8,
    borderWidth: 2,
    alignItems: 'center',
  },
  messTypeButtonTextSelected: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#fff',
  },
  messTypeContainer: {
    marginBottom: 50,
  },
  imageSelected: {
    width: '100%',
    height: 200,
    margin: 0,
  },
  infoTile: {
    width: '85%',
    height: 150,
    backgroundColor: '#54ae33',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    marginLeft: 15,
    marginRight: 15,
    borderRadius: 6,
  },
  mainContainer: {
    flex: 1,
    alignItems: 'stretch',
    width: '100%',
    paddingHorizontal: 25,
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  mainPreviewContainer: {
    flex: 1,
    alignItems: 'stretch',
    padding: 25,
    width: '100%',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  mapPreviewTile: {
    width: '95%',
    height: 175,
    backgroundColor: '#54ae33',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    marginVertical: 10,
    marginLeft: 8,
    borderRadius: 6,
  },
  paragraph: {
    textAlign: 'left',
    width: '100%',
    paddingLeft: 15,
    paddingRight: 15,
  },
  previewHeading: {
    textAlign: 'center',
    fontSize: 20,
    marginTop: 15,
    marginBottom: 15,
  },
  primaryHeading: {
    textAlign: 'center',
    fontSize: 25,
    marginTop: 50,
    marginBottom: 40,
  },
  progressBar: {
    marginTop: 50,
    width: 250,
    textAlign: 'center',
  },
  secondaryHeading: {
    textAlign: 'center',
    width: '100%',
  },
  subheading: {
    textAlign: 'left',
    width: '100%',
    fontSize: 15,
    fontWeight: "bold",
    paddingTop: 10,
    paddingLeft: 15,
    marginBottom: 5,
  },
  textInput: {
    height: 40,
    width: '80%',
    textAlign: 'center',
    borderColor: 'gray',
    borderRadius: 6,
    borderWidth: 1,
    marginBottom: 50,
    marginLeft: 20,
  },
  typeElement: {
    marginRight: 5,
    marginLeft: 5,
    backgroundColor: '#54ae33',
  },
});
